### ISSUE TITLE
jquery ajax vervangen door fetch

### ISSUE THREAD

**Issue by studentRocTilburg4** [studentRocTilburg4/wandelapp_issues#5]
jQuery wordt alleen gebruikt voor een AJAX request in routes.js.
Kan dit niet vervangen worden door de nieuwe fetch API?

**Comment by studentRocTilburg4** [comment]
jQuery wordt ook gebruikt in hikingapp.js. jQuery blijft dus nodig. Update van routes.js is in ieder geval wel nodig.

**Comment by WEBhicham** [comment]
is fixed
